#!/bin/bash

name=develop

echo $name

git co $name ; git pull ; git pull ; git co - 

#### ; git merge $name

echo -n "Perform MERGE $name onto this branch? (y/N)? "
read answer
if echo "$answer" | grep -iq "^y" ;then
    echo Merging…
    git merge $name
else
    echo Ok, bye. 
fi



